server {
    listen 80;
    server_name 3.88.39.239;

    root /var/www/html/yii2-app/web;  
    index index.php index.html;

    charset utf-8;

    access_log /var/log/nginx/yii2_access.log;
    error_log  /var/log/nginx/yii2_error.log;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;

        fastcgi_pass unix:/run/php/php8.1-fpm.sock;  # Update for your PHP version if needed
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~* /\. {
        deny all;
    }
}

