---
- name: Deploy Flask App
  hosts: all
  become: true
  vars_files:
    - vars.yml
  
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started
    
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
    
    - name: Install NGINX
      apt:
        name: nginx
        state: present
    
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        
    - name: Check if node is already in a swarm
      shell: docker info --format '{{'{{'}} .Swarm.LocalNodeState {{'}}'}}'
      register: swarm_status
      changed_when: false

    - name: Pull the latest Docker image
      shell: docker pull {{ docker_image }}
      become: yes

    - name: Update the Docker Swarm service
      shell: docker service update --image {{ docker_image }} yii2_app_service
      become: yes

