---
- name: Deploy Flask App
  hosts: all
  become: true
  vars_files:
    - vars.yml
  
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started
    
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
    
    - name: Install NGINX
      apt:
        name: nginx
        state: present
    
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        
    - name: Initialize Docker Swarm
      shell: docker swarm init --advertise-addr {{ swarm_ip }}
      register: swarm_init
      failed_when: "'This node is already part of a swarm' not in swarm_init.stderr and swarm_init.rc != 0"
      changed_when: "'This node is already part of a swarm' not in swarm_init.stderr"
      
    - name: Pull the latest Docker image
      shell: docker pull {{ docker_image }}
      become: yes
      
    - name: Check if the service exists
      shell: docker service ls --format '{{.Name}}' | grep -w yii2_app_service
      register: service_check
      ignore_errors: true
      changed_when: false
    
    - name: Remove existing Docker service if it exists
      shell: docker service rm yii2_app_service
      when: service_check.rc == 0
      become: true
    
    - name: Wait a moment for service cleanup
      pause:
        seconds: 5
      when: service_check.rc == 0
      
    - name: Create the Docker Swarm service
      shell: docker service create --name yii2_app_service --replicas 1 --publish 80:80 {{ docker_image }}
      become: true

